_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 5
                - 14
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.11
            "5": 0.19.4
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 16
epochs:
    value: 3
global_batch_index:
    value: 5326
learning_rate:
    value: 1e-05
loss_fn:
    value: KLDivLoss
optimizer:
    value: SGD
resumed:
    value: true
